### ISSUE TITLE
Gemini AI API

### ISSUE THREAD

**Issue by Bobby-is-the-worst** [tudoujunha/gemini-google-extension#1]
Not an issue, but how do you use the Gemini API in a chrome extension. Can you give some simple code that uses the API inside a chrome extension's JS script? Thx

**Comment by tudoujunha** [comment]
You can see in the official documentation how to call API in js scripts: [https://ai.google.dev/tutorials/node_quickstart](https://ai.google.dev/tutorials/node_quickstart)
