### ISSUE TITLE
[Feature Request] Search Engine

### ISSUE THREAD

**Issue by NiffirgkcaJ** [tudoujunha/gemini-google-extension#10]
Would it be possible for this add-on to inject into Startpage results also?

**Comment by BennettFourr** [comment]
I have a fork that does only startpage at https://github.com/BennettFourr/gemini-for-seach  you have to manualy install it.

**Comment by NiffirgkcaJ** [comment]
> I have a fork that does only startpage at https://github.com/BennettFourr/gemini-for-seach you have to manualy install it.

Pardon my ignorance, but I'm not sure what to do with those files.

**Comment by BennettFourr** [comment]
do you use firefox or chrome

**Comment by BennettFourr** [comment]
If firefox click on the xpi file in release one
If chrome download  chromium.zip and then follow this guide https://www.theseotoday.com/2022/09/how-to-add-extensions-to-chrome.html

**Comment by NiffirgkcaJ** [comment]
> If firefox click on the xpi file in release one If chrome download chromium.zip and then follow this guide https://www.theseotoday.com/2022/09/how-to-add-extensions-to-chrome.html

Thank you for your effort. I've tried it, but it still doesn't appear in Startpage.
