### ISSUE TITLE
Problems in theUK

### ISSUE THREAD

**Issue by G4DCP** [tudoujunha/gemini-google-extension#15]
I tried your extension and am having a problem:-
Failed to load response from Gemini:
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:streamGenerateContent?alt=sse: [400 ] User location is not supported for the API use without a billing account linked.

I have a paid personal account using AI in the UK.

Any ideas?

**Comment by tudoujunha** [comment]
You need to use a billing account link.
![image](https://github.com/tudoujunha/gemini-google-extension/assets/131859738/bf1aead8-ce18-4289-87aa-00fa0e9c2838)

https://ai.google.dev/gemini-api/docs/available-regions?unpaid-tier-unavailable
