### ISSUE TITLE
建议和反馈

### ISSUE THREAD

**Issue by Houtx** [tudoujunha/gemini-google-extension#3]
建议：
- [x] #5

反馈：
chrome120.0.6099.130版本非必现问题。
当chrome的搜索引擎默认为google时，直接在链接栏输入关键字后回车键搜索，右侧有一定几率不会出现gemini窗口。
![image](https://github.com/tudoujunha/gemini-google-extension/assets/17922172/1a3c312a-19e3-4bdf-b677-2f103db3ab06)
![image](https://github.com/tudoujunha/gemini-google-extension/assets/17922172/0cffc880-ef92-454a-9fa6-f4403e3208ee)

感谢作者！

**Comment by tudoujunha** [comment]
收到😀
