### ISSUE TITLE
建议增加一个API服务器的选项

### ISSUE THREAD

**Issue by siknet** [tudoujunha/gemini-google-extension#4]
可以自己设置中转服务器

**Comment by Hackforid** [comment]
+1.  
解决国内location限制和自己搭的api问题

**Comment by tudoujunha** [comment]
正在处理...下个版本解决...

**Comment by tudoujunha** [comment]
https://github.com/tudoujunha/gemini-google-extension/releases/tag/v0.1.2
已经添加自定义Endpoint
