### ISSUE TITLE
[Feature] You can add some feature/fucntionality to fetch transcript from youtube video pages and summarize the video in side panel

### ISSUE THREAD

**Issue by Greatz08** [tudoujunha/gemini-google-extension#7]
you can use same side panel to show the summary of the video in text that is been played currently by first fetching the transcript from current video and if there is no direct way then you can feed the youtube url to online transcript fetcher websites which can fetch the video transcript and give the text and then store that text and feed it to google gemini ai and make it summarize the the current video that is been played.If you are able to this much then you can further add websites like github itself and fetch all project content and make gemini summarize and give best key points in easy way so in that way you can expand this too and there are some open source project like glarity which are able to accomplish this but with gpt so you can take idea and can try with gemini to implement first in extension and then if possible in userscript because userscript also has its limit i guess maybe so not all thing you might be able to accomplish but still can try and explore that too and expand this project

**Comment by jxplvnvusa** [comment]
Thank you. I didn't know this functionality was possible. I'm working on a project where this would be helpful. Thanks!
